[BitTorrent]
Session\DefaultSavePath=/data/torrents/complete
Session\TempPath=/data/torrents/incomplete
Session\TempPathEnabled=true

[Preferences]
WebUI\Address=*
WebUI\AlternativeUIEnabled=false
WebUI\AuthSubnetWhitelistEnabled=false
WebUI\BanDuration=3600
WebUI\CSRFProtection=false
WebUI\ClickjackingProtection=true
WebUI\HostHeaderValidation=false
WebUI\HTTPS\Enabled=false
WebUI\LocalHostAuth=false
WebUI\MaxAuthenticationFailCount=5
WebUI\Port=8080
WebUI\SecureCookie=true
WebUI\SessionTimeout=3600
WebUI\Username=admin
